### ISSUE TITLE
I couldn't open the database file

### ISSUE THREAD

**Issue by bbkane** [tgangte/LocalCA#20]
When trying to run the migrations from the README, I ran into the following error:

```
$ python manage.py migrate
Traceback (most recent call last):
  File "/Users/jennykane/Git-GH/LocalCA/venv/lib/python3.13/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "/Users/jennykane/Git-GH/LocalCA/venv/lib/python3.13/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jennykane/Git-GH/LocalCA/venv/lib/python3.13/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/jennykane/Git-GH/LocalCA/venv/lib/python3.13/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jennykane/Git-GH/LocalCA/venv/lib/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 200, in get_new_connection
    conn = Database.connect(**conn_params)
sqlite3.OperationalError: unable to open database file
```

**Comment by tgangte** [comment]
Thanks for flagging this!  The database directory was empty and git did not track it, so it never got pushed. I've pushed a fix here, it should work now! https://github.com/tgangte/LocalCA/commit/18dfeae5135c2f9490173696cfe4c9dae21ce632
